# Generated by Django 3.0.8 on 2020-07-17 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clearcalapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='UserSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OG', 'organization'), ('VL', 'volunteer')], default='volunteer', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=16)),
                ('end', models.CharField(max_length=16)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='clearcalapi.Event')),
                ('volunteer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='clearcalapi.UserSubClass')),
            ],
        ),
    ]
