# Generated by Django 3.0.8 on 2020-07-20 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clearcalapi', '0002_auto_20200717_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='usersubclass',
            name='type',
            field=models.CharField(choices=[('VL', 'volunteer'), ('OG', 'organization')], max_length=32),
        ),
        migrations.AlterField(
            model_name='usersubclass',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
